### ISSUE TITLE
invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by waylew-lexis** [PaloAltoNetworks/terraform-provider-bridgecrew#17]
## Describe the bug

when trying to run plan using prisma access for any resource, I get this error ' Error: invalid character '<' looking for beginning of value
│
│   with data.bridgecrew_policies.policies,
│   on main.tf line 1, in data "bridgecrew_policies" "policies":
│    1: data "bridgecrew_policies" "policies" {

this is how my provider is configured
provider "bridgecrew" {
  accesskeyid = var.prisma_access_key_id
  secretkey = var.prisma_secret_key
  prisma = "https://app2.prismacloud.io"
}

when using bridgecrew token instead of prisma creds it seems to work. 
Is the provider not quite ready to be used with Prisma Cloud Security?

## Expected behavior

plan should not generate an error. 

## Steps to reproduce

1. run terraform plan 

## Your Environment

- Version used: 0.211
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile): windows desktop
- Link to your project:

**Comment by mwelch-mckinsey** [comment]
Same issue here. I tried "accesskeyid" (from looking at the source code) and "access_key_id" (from looking at the documentation).

**Comment by JamesWoolfenden** [comment]
it should be accesskeyid - ive fixed the docs. Havent managed to repro this error though, and yes it does work with prisma and bridgecrew
