### ISSUE TITLE
The provider should update remote polices when the policy file itself changes. 

### ISSUE THREAD

**Issue by mwelch-m** [PaloAltoNetworks/terraform-provider-bridgecrew#27]
### Is your feature request related to a problem?
When a YAML  policy file is updated, the terraform provider does not appear to update the policy in remote system (i.e. Bridgecrew or Prisma Cloud Code Security). It would be terrific if it did this. At the current time, we have to manually taint (or in newer Terraform versions, replace) the resource to update a policy

### Describe the solution you'd like
We would like to be able to update a YAML policy file and have that update be propagated to the remote system when our deployment CI executes.

**Comment by JamesWoolfenden** [comment]
Hi it should work this way. Which resource are you using? And is this PCC or bridgecrew?

**Comment by JamesWoolfenden** [comment]
@mwelch-m are you setting the source-code-hash?

**Comment by mwelch-m** [comment]
It appears we missed that attribute. Thank you.
