### ISSUE TITLE
Support custom YAML policies for Kubernetes framework

### ISSUE THREAD

**Issue by kkline-panw** [PaloAltoNetworks/terraform-provider-bridgecrew#29]
Presently, maintaining custom YAML policies for Kubernetes framework checks isn't supported.  Please amend the provider to allow this.  Thank you!

**Comment by JamesWoolfenden** [comment]
[v0.3.7](https://github.com/PaloAltoNetworks/terraform-provider-bridgecrew/tree/v0.3.7) should do it
